# Generated by Django 4.2.30 on 2026-05-06 05:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LegalDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("title", models.CharField(max_length=500)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("FIR", "First Information Report"),
                            ("AFFIDAVIT", "Affidavit"),
                            ("WITNESS_STATEMENT", "Witness Statement"),
                            ("BAIL_APPLICATION", "Bail Application"),
                            ("LEGAL_NOTICE", "Legal Notice"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=50,
                    ),
                ),
                ("file", models.FileField(upload_to="legal_documents/%Y/%m/%d/")),
                (
                    "file_hash",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("file_size_bytes", models.PositiveBigIntegerField()),
                ("mime_type", models.CharField(max_length=100)),
                ("page_count", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UPLOADED", "Uploaded"),
                            ("OCR_PROCESSING", "OCR In Progress"),
                            ("OCR_COMPLETE", "OCR Complete"),
                            ("CHUNKING", "Chunking In Progress"),
                            ("EMBEDDING", "Embedding In Progress"),
                            ("READY", "Ready for Querying"),
                            ("FAILED", "Processing Failed"),
                        ],
                        default="UPLOADED",
                        max_length=20,
                    ),
                ),
                ("raw_text", models.TextField(blank=True, default="")),
                (
                    "ocr_engine_used",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("processing_error", models.TextField(blank=True, default="")),
                ("session_id", models.UUIDField(db_index=True)),
                (
                    "chroma_collection_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
            ],
            options={
                "verbose_name": "Legal Document",
                "verbose_name_plural": "Legal Documents",
                "ordering": ["-created_at"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["session_id", "status"],
                        name="documents_l_session_c580ff_idx",
                    ),
                    models.Index(
                        fields=["file_hash"], name="documents_l_file_ha_272c9d_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DocumentChunk",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("chunk_index", models.PositiveIntegerField()),
                ("chunk_text", models.TextField()),
                ("page_number", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "section_label",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("char_start", models.PositiveIntegerField()),
                ("char_end", models.PositiveIntegerField()),
                ("text_hash", models.CharField(db_index=True, max_length=64)),
                ("chroma_vector_id", models.CharField(max_length=255, unique=True)),
                ("token_count", models.PositiveIntegerField()),
                ("is_embedded", models.BooleanField(db_index=True, default=False)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="documents.legaldocument",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Chunk",
                "verbose_name_plural": "Document Chunks",
                "ordering": ["chunk_index"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["document", "is_embedded"],
                        name="documents_d_documen_8b8a54_idx",
                    )
                ],
                "unique_together": {("document", "chunk_index")},
            },
        ),
    ]
