# Generated by Django 4.2.30 on 2026-05-06 05:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orchestration", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompiledDocument",
            fields=[
                (
                    "document_id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("status", models.CharField(default="ASSEMBLING", max_length=20)),
                ("template_name", models.CharField(blank=True, max_length=100)),
                ("assembled_html", models.TextField()),
                ("review_completion_pct", models.FloatField(default=0.0)),
                ("total_clauses", models.PositiveIntegerField(default=0)),
                ("approved_clauses", models.PositiveIntegerField(default=0)),
                ("export_pdf_path", models.CharField(blank=True, max_length=500)),
                ("export_docx_path", models.CharField(blank=True, max_length=500)),
                ("exported_at", models.DateTimeField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "query",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compiled_document",
                        to="orchestration.querysession",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReviewChecklistItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clause_index", models.PositiveIntegerField()),
                ("clause_text", models.TextField()),
                ("citation_string", models.CharField(blank=True, max_length=500)),
                ("source_vector_ids", models.JSONField(default=list)),
                ("verification_verdict", models.CharField(blank=True, max_length=30)),
                ("verification_score", models.FloatField(default=0.0)),
                ("is_null_field", models.BooleanField(default=False)),
                ("is_approved", models.BooleanField(default=False)),
                ("approved_at", models.DateTimeField(null=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_items",
                        to="compilation.compileddocument",
                    ),
                ),
            ],
            options={
                "ordering": ["clause_index"],
                "unique_together": {("document", "clause_index")},
            },
        ),
    ]
