# Generated by Django 4.2.30 on 2026-05-06 05:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="QuerySession",
            fields=[
                (
                    "query_id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("session_id", models.UUIDField(db_index=True)),
                ("raw_query", models.TextField()),
                ("status", models.CharField(default="PENDING", max_length=20)),
                ("intent", models.CharField(blank=True, max_length=50)),
                ("result_payload", models.JSONField(null=True)),
                ("verification_report", models.JSONField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(null=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["session_id", "created_at"],
                        name="orchestrati_session_5f5995_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AgentExecutionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("agent_name", models.CharField(max_length=100)),
                ("status", models.CharField(max_length=20)),
                ("started_at", models.DateTimeField(null=True)),
                ("completed_at", models.DateTimeField(null=True)),
                ("duration_ms", models.IntegerField(null=True)),
                ("error_detail", models.TextField(blank=True)),
                (
                    "query",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_logs",
                        to="orchestration.querysession",
                    ),
                ),
            ],
        ),
    ]
